### ISSUE TITLE
[bug] Flaky Menu Selenium Test: test_addition_of_transition_effect

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-utils#397]
This test has been failing randomly in the CI build:

```
FAIL: test_addition_of_transition_effect (test_project.tests.test_selenium.TestMenu)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 6[33](https://github.com/openwisp/openwisp-utils/actions/runs/10188501898/job/28230628510#step:6:34), in _callTestMethod
    method()
  File "/home/runner/work/openwisp-utils/openwisp-utils/tests/test_project/tests/test_selenium.py", line 228, in test_addition_of_transition_effect
    self.assertEqual(menu.value_of_css_property('transition'), transition)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 1292, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/unittest/case.py", line 753, in fail
    raise self.failureException(msg)
AssertionError: 'none' != 'none 0s ease 0s'
- none
+ none 0s ease 0s
```

**Comment by nemesifier** [comment]
Solved by bb7110c3a7db5cec7866e0e91548324d352183d9.
